export const USER_MOVIE_ADD = "USER_MOVIE_ADD";
export const USER_MOVIE_REMOVE = "USER_MOVIE_REMOVE";
export const USER_MOVIES_LOAD = "USER_MOVIES_LOAD";
export const USER_TV_LOAD = "USER_TV_LOAD";
export const USER_TV_ADD = "USER_TV_ADD";
export const USER_TV_REMOVE = "USER_TV_REMOVE";

export const MOVIE_SEARCH_RESULTS_LOAD = "MOVIE_SEARCH_RESULTS_LOAD";
export const MOVIE_SEARCH_RESULTS_CLEAR = "MOVIE_SEARCH_RESULTS_CLEAR";
export const TV_SEARCH_RESULTS_LOAD = "TV_SEARCH_RESULTS_LOAD";
export const TV_SEARCH_RESULTS_CLEAR = "TV_SEARCH_RESULTS_CLEAR";

export const MOVIE_DISCOVER_RESULTS_LOAD = "MOVIE_DISCOVER_RESULTS_LOAD";
export const TV_DISCOVER_RESULTS_LOAD = "TV_DISCOVER_RESULTS_LOAD";

export const USER_LOAD = "USER_LOAD";
export const USER_UNLOAD = "USER_UNLOAD";
export const USER_UPDATE = "USER_UPDATE";

export const FG_CREATE = "FG_CREATE";
export const FG_LOAD = "FG_LOAD";
export const FG_MEDIA_RECOMMENDATION_LOAD = "FG_MEDIA_RECOMMENDATION_LOAD";
export const FG_MEDIA_RECOMMENDATION_REMOVE = "FG_MEDIA_RECOMMENDATION_REMOVE";
export const FG_MEMBER_REMOVE = "FG_MEMBER_REMOVE";

export const AUTH_ADD = "AUTH_ADD";
export const AUTH_REMOVE = "AUTH_REMOVE";
