export const USER_MOVIE_ADD = "USER_MOVIE_ADD";
export const USER_MOVIE_REMOVE = "USER_MOVIE_REMOVE";
export const USER_MOVIES_LOAD = "USER_MOVIES_LOAD";
export const USER_TV_LOAD = "USER_TV_LOAD";
export const USER_TV_ADD = "USER_TV_ADD";
export const USER_TV_REMOVE = "USER_TV_REMOVE";

export const MOVIE_SEARCH_RESULTS_LOAD = "MOVIE_SEARCH_RESULTS_LOAD";
export const TV_SEARCH_RESULTS_LOAD = "TV_SEARCH_RESULTS_LOAD";

export const MOVIE_DISCOVER_RESULTS_LOAD = "MOVIE_DISCOVER_RESULTS_LOAD";
export const TV_DISCOVER_RESULTS_LOAD = "TV_DISCOVER_RESULTS_LOAD";
